---
- hosts: media_server
  tasks:
  - name: Ensure transmission is installed
    pacman:
      name: transmission-cli
      update-cache: yes
      state: present
  - name: Ensure apache is installed
    pacman:
      name: apache
      state: present
  - name: Ensure that apache is running
    service:
      name: httpd
      state: started
  - name: Ensure plex user is there
    user:
      name: plex
  - name: Ensure Aur user is created
    user:
      name: aur_builder
  - name: Give aur_builder right to execute pacman
    lineinfile:
      path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
      state: present
      line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
      validate: /usr/sbin/visudo -cf %s
      create: yes
  - name: Expand tmp
    mount:
      path: /tmp
      opts: remount,size=2G,noatime
      state: mounted
      src: tmpfs
      fstype: tmpfs
  - name: Install plex
    aur:
      name: plex-media-server
      use: makepkg
    become: yes
    become_user: aur_builder
  - name: Ensure plex is running
    service:
      name: plexmediaserver
      state: started
  - name: Install default web page
    copy:
      src: index.html
      dest: /srv/http/index.html
  - name: Configure apache to look into the vhost dir
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "^Include /etc/httpd/conf/vhost/*.conf"
      line: "Include /etc/httpd/conf/vhost/*.conf"
    notify: restart apache
  - name: Create vhost dir
    file:
      path: /etc/httpd/conf/vhost
      state: directory
      mode: 644
  - name: Create vhost for plex
    template:
      src: plex_vhost.j2
      dest: /etc/httpd/conf/vhost/zz-plex.conf
      mode: 644
    notify: restart apache
  - name: Create default vhost
    copy:
      src: default_vhost
      dest: /etc/httpd/conf/vhost/default.conf
      mode: 644
    notify: restart apache
  - name: Ensure apache modules are loaded
    lineinfile:
      path: /etc/httpd/conf/vhost/module.conf
      line: "LoadModule proxy_module modules/mod_proxy.so\nLoadModule proxy_http_module modules/mod_proxy_http.so"
      mode: 644
      create: yes
    notify: restart apache
  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
