---
- hosts: media_server
  tasks:
  - name: Ensure transmission is installed
    pacman:
      name: transmission-cli
      update-cache: yes
      state: present
  - name: Ensure apache is installed
    pacman:
      name: apache
      state: present
  - name: Ensure that apache is running
    service:
      name: apache
      state: started
